# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'DemoTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoTableView
    pod 'Cosmos'
    pod 'TinyConstraints'

  target 'DemoTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoTableViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
